"""
Adversarial export generator.

The reason this exists: the original test data was generated by the same mind
that wrote the parser, so it only ever exercised the assumptions the parser
already made. Every bug found in real use came from a property the generator
never produced -- a two-digit US date, emoji in the filename, fifteen
participants, a bot account, an extensionless attachment, "<Media omitted>"
interleaved with real files.

So this generator is built the other way round: from a catalogue of every
variation WhatsApp is known to emit, combined randomly, with exact ground truth
recorded alongside. If a combination breaks the pipeline, a test fails here
rather than a stranger's import failing later.

Nothing here is random for its own sake. Every axis below is a real difference
between two real exports.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta

# --- axes of real-world variation ---------------------------------------------

DATE_FORMATS = [
    ("DMY4", "{d:02d}/{m:02d}/{Y}"),      # 12/08/2023  (most of the world)
    ("DMY2", "{d:02d}/{m:02d}/{y:02d}"),  # 12/08/23
    ("MDY4", "{m}/{d}/{Y}"),              # 8/12/2023   (US)
    ("MDY2", "{m}/{d}/{y:02d}"),          # 8/12/23     (your export)
    ("YMD", "{Y}-{m:02d}-{d:02d}"),       # 2023-08-12
]

TIME_FORMATS = [
    ("24h", "{H:02d}:{M:02d}"),
    ("24hs", "{H:02d}:{M:02d}:{S:02d}"),
    ("12h", "{h}:{M:02d} {ap}"),
    ("12hU", "{h}:{M:02d} {AP}"),
    ("12hs", "{h}:{M:02d}:{S:02d} {AP}"),
]

# Android uses " - " after the stamp; iOS wraps the stamp in brackets.
LINE_SHAPES = ["android", "ios"]

# WhatsApp injects these invisibly; they have broken naive parsers for years.
INVISIBLE_MARKS = ["", "‎", "‏"]
AMPM_SPACES = [" ", " ", " "]

SENDER_POOL = [
    "Karan",
    "Rohit Sharma",
    "Kabir Rao",
    "Priya",
    "+91 98765 43210",
    "+91 98765 43210",
    "~Rohit",
    "Meta AI",
    "Dr. A. B. Rao",
    "आरव",                      # Devanagari name
    "דוד",                      # RTL name
    "Anna-Maria O'Brien",
    "J\U0001F346",                             # emoji in a display name
    "A very long display name that goes on and on and on",
]

TEXT_POOL = [
    "hey",
    "ok",
    "haha true",
    "what time?",
    "",                                        # genuinely empty body
    "line one\nline two\nline three",
    "check this https://example.com/x?a=1&b=2",
    "\U0001F602\U0001F602\U0001F602",          # emoji only
    "kal milte hain, ठीक है?",                 # code-mixed
    "a" * 3000,                                # very long
    "reminder: bring the file",                # contains a colon
    "12:30 pm tak aa jaana",                   # looks time-ish
    "‎plain text with an invisible mark",
]

MEDIA_BODIES = [
    ("<Media omitted>", None),
    ("image omitted", None),
    ("IMG-20240101-WA0001.jpg (file attached)", "IMG-20240101-WA0001.jpg"),
    ("PTT-20240101-WA0002.opus (file attached)", "PTT-20240101-WA0002.opus"),
    ("STK-20240101-WA0003.webp (file attached)", "STK-20240101-WA0003.webp"),
    ("DOC-20240101-WA0004. (file attached)", "DOC-20240101-WA0004."),
    ("<attached: 00000042-PHOTO-2024-01-01-09-00-00.jpg>",
     "00000042-PHOTO-2024-01-01-09-00-00.jpg"),
    ("VID-20240101-WA0005.mp4 (file attached)", "VID-20240101-WA0005.mp4"),
]

SYSTEM_BODIES = [
    "Messages and calls are end-to-end encrypted. No one outside of this chat, "
    "not even WhatsApp, can read or listen to them. Tap to learn more.",
    "Messages and calls are end-to-end encrypted. Only people in this chat can "
    "read, listen to or share them. Tap to learn more.",
    'Karan created group "Trip"',
    "Karan added Priya",
    "Priya left",
    "Karan removed Rohit",
    "+91 98765 43210 joined using this group's invite link",
    "Karan changed the subject to: New name",
    "Karan changed this group's icon",
    "You're now an admin",
    "Karan changed their phone number to a new number.",
    "Karan turned on disappearing messages.",
    "This group was upgraded to a community",
]

DELETED_BODIES = ["This message was deleted", "You deleted this message"]

LINE_ENDINGS = ["\n", "\r\n"]


@dataclass
class Expectation:
    """Exact ground truth for a generated export."""

    total_messages: int = 0          # everything the parser should return
    system_messages: int = 0
    media_messages: int = 0
    deleted_messages: int = 0
    attachments: int = 0             # media messages naming a real file
    senders: dict = field(default_factory=dict)
    date_format: str = ""
    time_format: str = ""
    shape: str = ""

    @property
    def real_messages(self) -> int:
        """Messages that survive into the database (system notices do not)."""
        return self.total_messages - self.system_messages


def _stamp(rng: random.Random, ts: datetime, date_fmt: str, time_fmt: str) -> str:
    ampm_space = rng.choice(AMPM_SPACES)
    hour12 = ts.hour % 12 or 12
    values = {
        "d": ts.day, "m": ts.month, "Y": ts.year, "y": ts.year % 100,
        "H": ts.hour, "M": ts.minute, "S": ts.second,
        "h": hour12,
        "ap": ("am" if ts.hour < 12 else "pm"),
        "AP": ("AM" if ts.hour < 12 else "PM"),
    }
    date_part = dict(DATE_FORMATS)[date_fmt].format(**values)
    time_part = dict(TIME_FORMATS)[time_fmt].format(**values)
    time_part = time_part.replace(" ", ampm_space) if "ap" in time_part.lower() \
        or "AM" in time_part or "PM" in time_part or "am" in time_part \
        or "pm" in time_part else time_part
    return f"{date_part}, {time_part}"


def generate(rng: random.Random, n_messages: int = 60,
             force: dict | None = None) -> tuple[str, Expectation]:
    """
    Build one randomised export plus its exact ground truth.

    `force` pins specific axes so a failing combination can be reproduced.
    """
    force = force or {}

    date_fmt = force.get("date_format") or rng.choice(DATE_FORMATS)[0]
    time_fmt = force.get("time_format") or rng.choice(TIME_FORMATS)[0]
    shape = force.get("shape") or rng.choice(LINE_SHAPES)
    eol = force.get("eol") or rng.choice(LINE_ENDINGS)

    # A date order is only *detectable* when a day above 12 appears. Force the
    # span wide enough that ambiguity is the exception, not the rule.
    start = datetime(2024, 1, 13, 9, 0)
    senders = rng.sample(SENDER_POOL, rng.randint(2, min(8, len(SENDER_POOL))))

    expectation = Expectation(date_format=date_fmt, time_format=time_fmt,
                              shape=shape)
    lines: list[str] = []
    ts = start

    for _ in range(n_messages):
        ts += timedelta(minutes=rng.randint(1, 400))
        mark = rng.choice(INVISIBLE_MARKS)
        stamp = _stamp(rng, ts, date_fmt, time_fmt)

        roll = rng.random()
        if roll < 0.10:
            body, sender, kind, attachment = rng.choice(SYSTEM_BODIES), None, "system", None
        elif roll < 0.30:
            body_text, attachment = rng.choice(MEDIA_BODIES)
            sender = rng.choice(senders)
            body = body_text
            kind = "media"
            if rng.random() < 0.3:               # captioned attachment
                body = body + "\n" + rng.choice(["look", "at the beach", "😂"])
        elif roll < 0.34:
            body, sender, kind, attachment = rng.choice(DELETED_BODIES), rng.choice(senders), "deleted", None
        else:
            body, sender, kind, attachment = rng.choice(TEXT_POOL), rng.choice(senders), "text", None

        if shape == "android":
            prefix = f"{mark}{stamp} - "
        else:
            prefix = f"{mark}[{stamp}] "

        line = prefix + (f"{sender}: {body}" if sender else body)
        lines.append(line)

        expectation.total_messages += 1
        if kind == "system":
            expectation.system_messages += 1
        elif kind == "media":
            expectation.media_messages += 1
            if attachment:
                expectation.attachments += 1
        elif kind == "deleted":
            expectation.deleted_messages += 1
        if sender:
            expectation.senders[sender] = expectation.senders.get(sender, 0) + 1

    return eol.join(lines) + eol, expectation


def describe(expectation: Expectation) -> str:
    return (f"date={expectation.date_format} time={expectation.time_format} "
            f"shape={expectation.shape} n={expectation.total_messages}")
